name: Build Jupyter-Book documentation ğŸ“–

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# ----------------------------------------------------------------------------------------------------------------------

defaults:
  run:
    shell: bash
    working-directory: pycram

jobs:
  test-and-build:
    name: Build Jupyter-Book documentation
    runs-on: ubuntu-latest

    steps:

      - name: Checkout ğŸ›
        uses: actions/checkout@v4

      - name: Install Graphviz
        run: |
          sudo apt update
          sudo apt install graphviz libgraphviz-dev -y

      # Install dependencies
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip # Implicitly uses requirements.txt for cache key

      - name: Update pip and setuptools ğŸ¼
        run: |
          pip install -U pip setuptools

      # ----------------------------------------------------------------------------------------------------------------
      - name: Install dependencies
        run: |
          pip install -r requirements.txt && pip install . && pip install -r doc/requirements.txt

#      - name: Install Jupyter-Book dependencies ğŸ¼
#        uses: py-actions/py-dependency-install@v4
#        with:
#          path: "requirements.txt"
#
#      # ----------------------------------------------------------------------------------------------------------------
#      - name: Install Jupyter-Book dependencies ğŸ“š
#        uses: py-actions/py-dependency-install@v4
#        with:
#          path: "doc/requirements.txt"
#
      # ----------------------------------------------------------------------------------------------------------------
      - name: Build Jupyter-Book documentation ğŸ“
        if: ${{ !env.ACT }}
        run: |
          jupyter-book build doc/source

      - name: Upload artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: pycram-doc
          path: "pycram/doc/source/_build/html"
